[project]
name = "documentation-assistant"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "crawl4ai>=0.9.2",
    "langchain-chroma>=1.1.0",
    "langchain-classic>=1.0.8",
    "langchain-core>=1.5.3",
    "langchain-huggingface>=1.2.2",
    "langchain-ollama>=1.1.0",
    "python-dotenv>=1.2.2",
    "ultimate-sitemap-parser>=1.8.1",
]
